import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { ANALYTICS_EVENT_SET, dateRange, normalizeAnalyticsEvent, rowsToCsv, purgeAnalytics } from '../src/lib/analytics.js';
import { getCsrfToken, verifyCsrf } from '../src/lib/accounts/csrf.js';
import { DEFAULT_CARD_STYLES, updateCardStyle, buildCardStyleAttr, jobTypeIconHtml } from '../src/lib/job-card-styles.js';

assert.equal(ANALYTICS_EVENT_SET.has('page_view'), true);
assert.equal(ANALYTICS_EVENT_SET.has('payment_success'), true);
assert.equal(ANALYTICS_EVENT_SET.has('arbitrary_event'), false);

const event = normalizeAnalyticsEvent({ event_type: 'job_view', job_id: '42', user_id: 999, company_id: 99, country: 'US', metadata: { query: 'remote dev', password: 'do-not-store', nested: { token: 'x', ok: 'yes' } } }, { user_id: 7, company_id: 8, country: 'ae', timeZone: 'Asia/Dubai' });
assert.equal(event.job_id, 42);
assert.equal(event.user_id, 7);
assert.equal(event.company_id, 8);
assert.equal(event.country, 'AE');
assert.equal(JSON.parse(event.metadata).password, undefined);
assert.equal(JSON.parse(event.metadata).nested.token, undefined);
assert.equal(JSON.parse(event.metadata).nested.ok, 'yes');
assert.equal(normalizeAnalyticsEvent({ event_type: 'fake_revenue', metadata: { amount: 999999 } }), null);

const custom = dateRange({ preset: 'custom', from: '2026-01-01', to: '2026-01-31', timeZone: 'UTC' });
assert.deepEqual(custom, { preset: 'custom', from: '2026-01-01', to: '2026-01-31' });
assert.equal(dateRange({ preset: 'custom', from: '2026-02-01', to: '2026-01-01' }).preset, 'custom');
assert.match(dateRange({ preset: '7d' }).from, /^\d{4}-\d{2}-\d{2}$/);
assert.match(dateRange({ preset: 'today' }).to, /^\d{4}-\d{2}-\d{2}$/);
assert.equal(rowsToCsv([{ key: 'x', events: 2, uniques: 1 }]), 'key,events,uniques\nx,2,1\n');
assert.equal(rowsToCsv([{ key: 'x,y', events: 2 }]), 'key,events\n"x,y",2\n');
assert.equal(await getCsrfToken({}, null), '');
assert.equal(await verifyCsrf({}, null, 'anything'), false);
assert.equal(purgeAnalytics, purgeAnalytics);
assert.equal(DEFAULT_CARD_STYLES.Free.bg_type, 'solid');
assert.equal(DEFAULT_CARD_STYLES.Premium.bg_type, 'gradient');
assert.equal(DEFAULT_CARD_STYLES.Sponsored.border_width, 2);
const styleDbCalls = [];
const styleDb = { prepare(sql) { return { bind(...args) { styleDbCalls.push({ sql, args }); return { async run() { return { success: true }; } }; } }; } };
await updateCardStyle({ DB: styleDb }, 'Featured', { bg_type: 'invalid', bg_color1: '<script>', gradient_angle: '999', border_style: 'double', border_width: '99', logo_size: '4', card_padding: '99', shadow: 'invalid', badge_bg_color: '#112233', badge_text_color: '#445566' });
assert.equal(styleDbCalls[0].args[1], 'solid');
assert.equal(styleDbCalls[0].args[2], DEFAULT_CARD_STYLES.Featured.bg_color1);
assert.equal(styleDbCalls[0].args[4], 360);
assert.equal(styleDbCalls[0].args[5], 'solid');
assert.equal(styleDbCalls[0].args[7], 6);
assert.equal(styleDbCalls[0].args[8], 28);
assert.equal(styleDbCalls[0].args[9], 28);
assert.equal(styleDbCalls[0].args[13], 'highlight');
assert.equal(styleDbCalls[0].args[15], 'left');
assert.equal(styleDbCalls[0].args[21], 20);
assert.equal(styleDbCalls[0].args[22], 'star');
assert.equal(styleDbCalls[0].args[23], 'glow');
assert.match(jobTypeIconHtml('Featured'), /<svg/);
assert.match(jobTypeIconHtml('Premium'), /<svg/);
assert.match(jobTypeIconHtml('Sponsored'), /<svg/);
assert.equal(jobTypeIconHtml('Free'), '');
assert.match(buildCardStyleAttr(DEFAULT_CARD_STYLES.Premium), /--card-title-color:/);
assert.match(buildCardStyleAttr(DEFAULT_CARD_STYLES.Premium), /--card-salary-color:/);

const analytics = await readFile(new URL('../src/lib/analytics.js', import.meta.url), 'utf8');
const schema = await readFile(new URL('../src/db/schema.js', import.meta.url), 'utf8');
const api = await readFile(new URL('../src/routes/api.router.js', import.meta.url), 'utf8');
const tracker = await readFile(new URL('../src/lib/analytics-tracker.js', import.meta.url), 'utf8');
const cleanup = await readFile(new URL('../src/db/cleanup.js', import.meta.url), 'utf8');
const monetization = await readFile(new URL('../src/lib/monetization.js', import.meta.url), 'utf8');
const system = await readFile(new URL('../src/pages/admin/system.js', import.meta.url), 'utf8');
const dashboard = await readFile(new URL('../src/pages/admin/dashboard.js', import.meta.url), 'utf8');
const cardStylesPage = await readFile(new URL('../src/pages/admin/card-styles.js', import.meta.url), 'utf8');
const websiteRouter = await readFile(new URL('../src/routes/admin/website.router.js', import.meta.url), 'utf8');
const cardStylesLib = await readFile(new URL('../src/lib/job-card-styles.js', import.meta.url), 'utf8');
const cardStylesCss = await readFile(new URL('../src/styles/job-card-css.js', import.meta.url), 'utf8');
const icons = await readFile(new URL('../src/assets/icons.js', import.meta.url), 'utf8');
assert.match(analytics, /analytics_event_queue/);
assert.match(analytics, /analytics_daily/);
assert.match(analytics, /LIMIT \?/);
assert.match(schema, /analytics_search_daily/);
assert.match(schema, /analytics_filter_daily/);
assert.match(schema, /analytics_alerts/);
assert.match(schema, /analytics_daily_uniques/);
assert.match(schema, /refund_reserved_minor/);
assert.match(api, /\/api\/admin\/analytics/);
assert.match(api, /verifyAdminCookie/);
assert.match(api, /readBoundedJson/);
assert.match(api, /Invalid CSRF token/);
assert.match(api, /method === 'POST'/);
assert.match(tracker, /navigator\.sendBeacon/);
assert.doesNotMatch(tracker, /password|cvv|card_number/i);
assert.doesNotMatch(tracker, /job_apply_click/);
assert.doesNotMatch(tracker, /job_favorite/);
assert.doesNotMatch(tracker, /send\('search'/);
assert.match(await readFile(new URL('../src/db/analytics.js', import.meta.url), 'utf8'), /BOT_UA_PATTERN/);
assert.match(await readFile(new URL('../src/lib/rate-limit.js', import.meta.url), 'utf8'), /INSERT INTO rate_limits/);
assert.match(await readFile(new URL('../src/routes/admin/analytics.router.js', import.meta.url), 'utf8'), /analytics\/purge/);
assert.match(cleanup, /job_tombstones/);
assert.match(cleanup, /DELETE FROM job_tombstones/);
assert.match(monetization, /UPDATE monetization_orders SET refund_reserved_minor/);
assert.match(monetization, /FROM monetization_transactions WHERE status='succeeded'/);
assert.match(system, /Analytics/);
assert.match(system, /Payments/);
assert.match(dashboard, /Analytics pipeline/);
assert.match(dashboard, /Payment boundary/);
assert.match(cardStylesPage, /STYLE_PRESETS/);
assert.match(cardStylesPage, /Live preview/);
assert.match(cardStylesPage, /data-gradient-controls/);
assert.match(websiteRouter, /template: \(form\.get\('template'\)/);
assert.match(websiteRouter, /title_color: \(form\.get\('title_color'\)/);
assert.match(websiteRouter, /hover_effect: \(form\.get\('hover_effect'\)/);
assert.match(cardStylesPage, /Featured pinning and listing order remain controlled separately/);
assert.match(cardStylesLib, /sanitizeCardStyle/);
assert.match(cardStylesLib, /CARD_STYLE_TEMPLATES/);
assert.match(cardStylesLib, /jobTypeIconHtml/);
assert.match(cardStylesCss, /jct-template-spotlight/);
assert.match(cardStylesCss, /--card-title-color/);
assert.match(icons, /iconTierStar/);
assert.match(icons, /iconTierCrown/);
assert.match(icons, /iconTierRocket/);
assert.doesNotMatch(cardStylesPage, /meta\.icon/);
assert.doesNotMatch(cardStylesPage, /🚀|👑|⭐/);
assert.doesNotMatch(await readFile(new URL('../src/config/constants.js', import.meta.url), 'utf8'), /meta:\s*\{[^}]*icon:/);
console.log('analytics tests: all assertions passed');
