import { baseLayout } from '../layout/base-layout.js';
import { getSettings } from '../lib/settings.js';
import { getCategoryData } from '../lib/categories.js';
import { formatMoneyMinor, listProducts, paymentProviderStatus } from '../lib/monetization.js';
import { escapeHtml } from '../lib/entities.js';

export async function renderPricingPage(base, env, user = null) {
  const [settings, categories, products] = await Promise.all([getSettings(env), getCategoryData(env), listProducts(env, { activeOnly: true })]);
  const provider = paymentProviderStatus(env);
  const productsAvailable = products.filter(product => (product.type !== 'featured_job' || settings.monetization_featured_enabled !== '0') && (product.type !== 'sponsored_job' || settings.monetization_sponsored_enabled !== '0'));
  const content = `<main class="page-sm pricing-page">
    <style>.pricing-page{padding:42px 18px 72px}.pricing-hero{text-align:center;max-width:680px;margin:0 auto 28px}.pricing-hero .eyebrow{color:var(--brand);font-size:10px;font-weight:850;letter-spacing:1.4px;text-transform:uppercase}.pricing-hero h1{margin:9px 0 10px;font:800 32px var(--font-heading,sans-serif);color:var(--ink)}.pricing-hero p{margin:0;color:var(--ink2);font-size:14px;line-height:1.7}.pricing-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px}.pricing-card{display:flex;flex-direction:column;min-height:260px;padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--surface);box-shadow:var(--shadow);position:relative}.pricing-card h2{margin:0;color:var(--ink);font:800 16px var(--font-heading,sans-serif)}.pricing-card p{color:var(--ink2);font-size:11px;line-height:1.6;min-height:54px}.pricing-price{margin:13px 0;color:var(--brand);font:850 25px var(--font-heading,sans-serif)}.pricing-price small{font:600 10px var(--font-body,sans-serif);color:var(--ink3)}.pricing-meta{display:flex;gap:6px;flex-wrap:wrap;color:var(--ink3);font-size:10px}.pricing-cta{margin-top:auto;display:inline-flex;justify-content:center;align-items:center;min-height:38px;border-radius:10px;background:var(--brand);color:#fff;text-decoration:none;font-size:11px;font-weight:800}.pricing-cta.disabled{background:var(--surface2);color:var(--ink3);cursor:not-allowed}.pricing-note{max-width:760px;margin:20px auto 0;padding:12px 14px;border:1px solid rgba(245,158,11,.25);border-radius:11px;background:rgba(245,158,11,.08);color:var(--ink2);font-size:11px;line-height:1.6}.pricing-empty{text-align:center;padding:24px;color:var(--ink3)}@media(max-width:1050px){.pricing-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.pricing-page{padding:30px 14px 52px}.pricing-hero h1{font-size:27px}.pricing-grid{grid-template-columns:1fr}.pricing-card{min-height:0}}</style>
    <div class="pricing-hero"><div class="eyebrow">EMPLOYER PRODUCTS</div><h1>Promote the roles that matter</h1><p>Choose a clearly defined employer product. Prices and durations are managed server-side and shown directly from the active catalog.</p></div>
    ${productsAvailable.length ? `<div class="pricing-grid">${productsAvailable.map(product => `<article class="pricing-card"><h2>${escapeHtml(product.name)}</h2><p>${escapeHtml(product.description || '')}</p><div class="pricing-price">${escapeHtml(formatMoneyMinor(product.price_minor, product.currency))} <small>one time</small></div><div class="pricing-meta"><span>${Number(product.duration_days || 0)} days</span><span>${escapeHtml(product.currency)}</span><span>${escapeHtml(product.type)}</span></div><a class="pricing-cta ${provider.checkoutConfigured ? '' : 'disabled'}" ${provider.checkoutConfigured ? `href="/company/dashboard"` : 'aria-disabled="true"'}>${provider.checkoutConfigured ? 'Continue' : 'Payment setup required'}</a></article>`).join('')}</div>` : '<div class="pricing-empty">No employer products are currently available.</div>'}
    <div class="pricing-note"><strong>Payment status:</strong> ${escapeHtml(provider.message)} This page never accepts a client-supplied price and never represents a pending order as paid.</div>
  </main>`;
  const robots = provider.checkoutConfigured ? '' : 'noindex, nofollow';
  return baseLayout(`Pricing — ${settings.site_name}`, 'Employer products and pricing', `${base}/pricing`, '', content, '', robots, settings, categories, null, null, null, user);
}
